require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AuthenticateController do

  # This should return the minimal set of attributes required to create a valid
  # Authenticate. As you add validations to Authenticate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AuthenticatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all authenticates as @authenticates" do
      authenticate = Authenticate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:authenticates).should eq([authenticate])
    end
  end

  describe "GET show" do
    it "assigns the requested authenticate as @authenticate" do
      authenticate = Authenticate.create! valid_attributes
      get :show, {:id => authenticate.to_param}, valid_session
      assigns(:authenticate).should eq(authenticate)
    end
  end

  describe "GET new" do
    it "assigns a new authenticate as @authenticate" do
      get :new, {}, valid_session
      assigns(:authenticate).should be_a_new(Authenticate)
    end
  end

  describe "GET edit" do
    it "assigns the requested authenticate as @authenticate" do
      authenticate = Authenticate.create! valid_attributes
      get :edit, {:id => authenticate.to_param}, valid_session
      assigns(:authenticate).should eq(authenticate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Authenticate" do
        expect {
          post :create, {:authenticate => valid_attributes}, valid_session
        }.to change(Authenticate, :count).by(1)
      end

      it "assigns a newly created authenticate as @authenticate" do
        post :create, {:authenticate => valid_attributes}, valid_session
        assigns(:authenticate).should be_a(Authenticate)
        assigns(:authenticate).should be_persisted
      end

      it "redirects to the created authenticate" do
        post :create, {:authenticate => valid_attributes}, valid_session
        response.should redirect_to(Authenticate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved authenticate as @authenticate" do
        # Trigger the behavior that occurs when invalid params are submitted
        Authenticate.any_instance.stub(:save).and_return(false)
        post :create, {:authenticate => {  }}, valid_session
        assigns(:authenticate).should be_a_new(Authenticate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Authenticate.any_instance.stub(:save).and_return(false)
        post :create, {:authenticate => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested authenticate" do
        authenticate = Authenticate.create! valid_attributes
        # Assuming there are no other authenticates in the database, this
        # specifies that the Authenticate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Authenticate.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => authenticate.to_param, :authenticate => { "these" => "params" }}, valid_session
      end

      it "assigns the requested authenticate as @authenticate" do
        authenticate = Authenticate.create! valid_attributes
        put :update, {:id => authenticate.to_param, :authenticate => valid_attributes}, valid_session
        assigns(:authenticate).should eq(authenticate)
      end

      it "redirects to the authenticate" do
        authenticate = Authenticate.create! valid_attributes
        put :update, {:id => authenticate.to_param, :authenticate => valid_attributes}, valid_session
        response.should redirect_to(authenticate)
      end
    end

    describe "with invalid params" do
      it "assigns the authenticate as @authenticate" do
        authenticate = Authenticate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Authenticate.any_instance.stub(:save).and_return(false)
        put :update, {:id => authenticate.to_param, :authenticate => {  }}, valid_session
        assigns(:authenticate).should eq(authenticate)
      end

      it "re-renders the 'edit' template" do
        authenticate = Authenticate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Authenticate.any_instance.stub(:save).and_return(false)
        put :update, {:id => authenticate.to_param, :authenticate => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested authenticate" do
      authenticate = Authenticate.create! valid_attributes
      expect {
        delete :destroy, {:id => authenticate.to_param}, valid_session
      }.to change(Authenticate, :count).by(-1)
    end

    it "redirects to the authenticates list" do
      authenticate = Authenticate.create! valid_attributes
      delete :destroy, {:id => authenticate.to_param}, valid_session
      response.should redirect_to(authenticates_url)
    end
  end

end
