require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClientLocationsController do

  # This should return the minimal set of attributes required to create a valid
  # ClientLocation. As you add validations to ClientLocation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClientLocationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all client_locations as @client_locations" do
      client_location = ClientLocation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:client_locations).should eq([client_location])
    end
  end

  describe "GET show" do
    it "assigns the requested client_location as @client_location" do
      client_location = ClientLocation.create! valid_attributes
      get :show, {:id => client_location.to_param}, valid_session
      assigns(:client_location).should eq(client_location)
    end
  end

  describe "GET new" do
    it "assigns a new client_location as @client_location" do
      get :new, {}, valid_session
      assigns(:client_location).should be_a_new(ClientLocation)
    end
  end

  describe "GET edit" do
    it "assigns the requested client_location as @client_location" do
      client_location = ClientLocation.create! valid_attributes
      get :edit, {:id => client_location.to_param}, valid_session
      assigns(:client_location).should eq(client_location)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClientLocation" do
        expect {
          post :create, {:client_location => valid_attributes}, valid_session
        }.to change(ClientLocation, :count).by(1)
      end

      it "assigns a newly created client_location as @client_location" do
        post :create, {:client_location => valid_attributes}, valid_session
        assigns(:client_location).should be_a(ClientLocation)
        assigns(:client_location).should be_persisted
      end

      it "redirects to the created client_location" do
        post :create, {:client_location => valid_attributes}, valid_session
        response.should redirect_to(ClientLocation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved client_location as @client_location" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClientLocation.any_instance.stub(:save).and_return(false)
        post :create, {:client_location => {  }}, valid_session
        assigns(:client_location).should be_a_new(ClientLocation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClientLocation.any_instance.stub(:save).and_return(false)
        post :create, {:client_location => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested client_location" do
        client_location = ClientLocation.create! valid_attributes
        # Assuming there are no other client_locations in the database, this
        # specifies that the ClientLocation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClientLocation.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => client_location.to_param, :client_location => { "these" => "params" }}, valid_session
      end

      it "assigns the requested client_location as @client_location" do
        client_location = ClientLocation.create! valid_attributes
        put :update, {:id => client_location.to_param, :client_location => valid_attributes}, valid_session
        assigns(:client_location).should eq(client_location)
      end

      it "redirects to the client_location" do
        client_location = ClientLocation.create! valid_attributes
        put :update, {:id => client_location.to_param, :client_location => valid_attributes}, valid_session
        response.should redirect_to(client_location)
      end
    end

    describe "with invalid params" do
      it "assigns the client_location as @client_location" do
        client_location = ClientLocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClientLocation.any_instance.stub(:save).and_return(false)
        put :update, {:id => client_location.to_param, :client_location => {  }}, valid_session
        assigns(:client_location).should eq(client_location)
      end

      it "re-renders the 'edit' template" do
        client_location = ClientLocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClientLocation.any_instance.stub(:save).and_return(false)
        put :update, {:id => client_location.to_param, :client_location => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested client_location" do
      client_location = ClientLocation.create! valid_attributes
      expect {
        delete :destroy, {:id => client_location.to_param}, valid_session
      }.to change(ClientLocation, :count).by(-1)
    end

    it "redirects to the client_locations list" do
      client_location = ClientLocation.create! valid_attributes
      delete :destroy, {:id => client_location.to_param}, valid_session
      response.should redirect_to(client_locations_url)
    end
  end

end
