source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.5'
# Use postgresql as the database for Active Record
gem 'pg'
gem 'foreigner' # Used for foreign-key relations

# OmniAuth used for LDAP authentication
gem 'omniauth-ldap'
gem 'hashie', '~> 3.3.1'

# RocketPants gem for building API
#gem 'rocket_pants', '~> 1.0'

# Front-end dependencies handled by browser-plugin

# Gems used when running tests.
# Taken from https://github.com/devleorepo/bountyboard/
group :test do
  gem 'rspec-rails', '~> 3.0.0'
  gem 'rspec-mocks', '~> 3.0.0'
  gem 'rspec-activemodel-mocks', '~> 1.0.1'
  # uncomment this gem when upgrading to rspec 3
  gem 'rspec-its', '~> 1.0.1' # Support for its syntax

  # Support for stubbing model in view specs
  gem 'capybara'
  gem 'rake'
  gem 'email_spec'
  gem 'timecop'
  gem 'simplecov', :require => false
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'watchr'
end

gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',                    group: :development
