default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  username: pi_pwt_railservice_login
  password: <%= ENV['PI_PWT_LOGIN_PASS'] %>
  database: pi_pwt_railservice_development

test:
  <<: *default
  database: pi_pwt_railservice_test

# production:
#   <<: *default
#   database: pi_pwt_railservice_production
#   username: pi_pwt_railservice


